# stage: development for React
FROM node:23-slim

# ⁡⁢⁣⁣рабочая папка внутри контейнера⁡
WORKDIR /app

# ⁡⁢⁣⁣копируем только манифесты и ставим зависимости⁡
COPY package*.json ./
RUN npm install

# ⁡⁢⁣⁣пробрасываем исходники внутрь (чтобы правки сразу отражались)⁡
VOLUME ["/app/node_modules"]

# ⁡⁢⁣⁣прокидываем порт CRA-dev-server⁡
EXPOSE 3000

# ⁡⁢⁣⁣ENV: чтобы CRA слушал на 0.0.0.0, а не на localhost (иначе из Docker-сети недоступно)⁡
ENV HOST=0.0.0.0

# ⁡⁢⁣⁡⁢⁣⁣ENV: включаем polling-mode для отслеживания изменений файлов внутри контейнера⁡
ENV CHOKIDAR_USEPOLLING=true

# ⁡⁢⁣⁣запускаем команду разработки⁡
CMD ["npm", "start"]