FROM python:3.13.3-alpine

# ⁡⁢⁣⁣Устанавливаем рабочую директорию внутри контейнера⁡
WORKDIR /app

# ⁡⁢⁣⁡⁢⁣⁣Копируем зависимости⁡
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ⁡⁢⁣⁣но Python не видит папку app как импортируемый модуль, потому что ⁡
# ⁡⁢⁣⁣tests/test_api.py делает from app.main import app, но интерпретатор не видит app/ как пакет.⁡
ENV PYTHONPATH=/app

# ⁡⁢⁣⁣Копируем весь код проекта (app + tests + init_db.py)⁡
COPY ./app ./app
COPY ./tests ./tests
COPY ./init_db.py ./init_db.py

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]